# blue.yaml (stable/current version)
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: digits-server-blue
  namespace: kubeflow
  annotations:
    sidecar.istio.io/inject: "false"
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    app: digits-server
    version: blue
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 2
    containers:
    - name: kserve-container
      image: mnist_tf:v1
      command: ["python", "/app/server.py"]
      args: ["v1"]
      ports:
      - containerPort: 8686
        name: mnist-port
        protocol: TCP
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
