FROM python:3.10

USER root

RUN pip install --no-cache-dir \
    boto3 \
    tensorflow \
    numpy \
    kserve
WORKDIR /app

COPY server.py /app/server.py
COPY model /app/model/1/

USER 1000

ENTRYPOINT ["python", "/app/server.py"]